// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ecomence_Cart.CartModel;

namespace ecomence_Cart.Migrations
{
    [DbContext(typeof(CartDb))]
    partial class CartDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ecomence_Cart.CartModel.Cart", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ItemName")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpDatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("phoneNumbers")
                        .HasColumnType("integer");

                    b.HasKey("ItemID");

                    b.ToTable("CarT");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            AddedTime = new DateTime(2023, 11, 25, 19, 31, 28, 422, DateTimeKind.Utc).AddTicks(7975),
                            ItemName = "Air-Max",
                            Quantity = 1,
                            UnitPrice = 1000.0,
                            phoneNumbers = 20303346
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
